# Generated by Django 4.1.6 on 2023-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='loai',
            field=models.TextField(default='clothe', max_length=255),
        ),
    ]
