# Generated by Django 4.1.6 on 2023-05-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentModel',
        ),
    ]
