# Generated by Django 4.1.7 on 2023-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loai',
            field=models.TextField(default='book', max_length=255),
        ),
    ]
